#!/usr/bin/env ruby

require_relative "nom"

nom = Nom.new

cmd = ARGV.shift
cmd = "status" if cmd.nil?

case cmd
when "nom"
    raise "Please specify food and kcal" if ARGV.size < 2
    kcal = ARGV.pop
    description = ARGV.join(" ")
    nom.nom(Date.today, kcal, description)
    nom.status()
when "weight"
    raise "Please specify weight" if ARGV.size != 1
    weight = ARGV.pop.to_f
    nom.weight(Date.today, weight)
when "plot"
    nom.plot()
when "search"
    nom.search(ARGV.join(" "))
when "status"
    nom.status()
when "help"
    puts "Available subcommands: nom, weight, plot, search, status, help."
else
    puts "Unknown subcommand"
end
